<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDN7Qfxz\srcApp_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDN7Qfxz/srcApp_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerDN7Qfxz.legacy');

    return;
}

if (!\class_exists(srcApp_KernelProdContainer::class, false)) {
    \class_alias(\ContainerDN7Qfxz\srcApp_KernelProdContainer::class, srcApp_KernelProdContainer::class, false);
}

return new \ContainerDN7Qfxz\srcApp_KernelProdContainer([
    'container.build_hash' => 'DN7Qfxz',
    'container.build_id' => '1485db64',
    'container.build_time' => 1630860599,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerDN7Qfxz');
